### ISSUE TITLE
Not process [node:nid] token in title for the new node

### ISSUE THREAD

**Issue by kleomash** [backdrop-contrib/auto_entitylabel#1]
Hi!

I need autofill title for node as  'Order # nid from date'.

I plased 'Order [node:nid] from [node:created:short]' into the 'Pattern for the title'. But it works only if I resaved early created node. For the new node I get empty space for node nid token.

What's the reason?

**Comment by Rich-DR** [comment]
Same problem: I am trying to autofill node titles using the replacement pattern [node:nid], and it only works when re-saving the node.

**Comment by yorkshire-pudding** [comment]
There's an explanation for this in the related ticket of backdrop-contrib/auto_nodetitle/issues/26

**Comment by argiepiano** [comment]
Paraphrasing that posting pointed out by @yorkshire-pudding: This is a limitation that can't be overcome due to the architecture of the module. The title is set within hook_entity_presave(). At that point the id of the entity is not yet known, as it hasn't been saved yet. 

I just posted a workaround in that module queue:
https://github.com/backdrop-contrib/auto_nodetitle/issues/26#issuecomment-1770942937
